name: ofoq_kourosh_assessment
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  go_router: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner: # dart run build_runner build
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Estedad
      fonts:
        - asset: fonts/Estedad-FD-Thin.ttf
          weight: 100
        - asset: fonts/Estedad-FD-ExtraLight.ttf
          weight: 200
        - asset: fonts/Estedad-FD-Light.ttf
          weight: 300
        - asset: fonts/Estedad-FD-Regular.ttf
          weight: 400
        - asset: fonts/Estedad-FD-Medium.ttf
          weight: 500
        - asset: fonts/Estedad-FD-SemiBold.ttf
          weight: 600
        - asset: fonts/Estedad-FD-Bold.ttf
          weight: 700
        - asset: fonts/Estedad-FD-ExtraBold.ttf
          weight: 800
        - asset: fonts/Estedad-FD-Black.ttf
          weight: 900
